SocialSweet\RecruitmentBundle\Entity\User:
    type:  entity
    table: user
    fields:
        id:
          id: true
          type: integer
          column: id
          generator:
            strategy: AUTO

        updatedAt:
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update

        firstname:
          type: string
          length: 128
          nullable: true

        lastname:
          type: string
          length: 128
          nullable: true

        facebookID:
          type: string
          length: 128
          nullable: true

        facebook_access_token:
          type: string
          length: 128
          nullable: true