services:
#    social_sweet_recruitment.example:
#        class: SocialSweet\RecruitmentBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    app.provider.oauth:
        class: SocialSweet\RecruitmentBundle\Security\OAuthUserProvider
        arguments:
            - '@fos_user.user_manager'
            - [facebook: facebook_id]